steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pathXplorer-backend', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'app-name', '--image', 'gcr.io/$PROJECT_ID/app-name', '--platform', 'managed', '--region', 'asia-southeast2']
images:
  - 'gcr.io/$PROJECT_ID/app-name'
